version: "3.8"  # Using a specific Docker Compose version

services:
  catalogdb:
    container_name: catalogdb  # Optional: Makes it easier to reference the container by name
    environment:
      - POSTGRES_USER=postgres   # Specify the database user
      - POSTGRES_PASSWORD=postgres  # Specify the password
      - POSTGRES_DB=CatalogDb  # Specify the database name
    restart: always
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_catalog:/var/lib/postgresql/data # Persistent data storage for PostgreSQL